### ISSUE TITLE
There's nothing here!

### ISSUE THREAD

**Issue by colwellkr** [timw4mail/HummingBirdAnimeClient#2]
Currently if a Manga list (and possibly anime list) is empty and you try to visit its page PHP throws an error and will not let you proceed further.  Demonstrated: http://mu.aryz.us/index.php/manga/all
An empty page with "There's nothing here!" for any empty lists seems appropriate.  Not just for manga, but for any list that is empty like http://mu.aryz.us/index.php/anime/dropped .

Thanks!

**Comment by timw4mail** [comment]
Fixed with 54371bf76ad12f171c59116b0e2a6ca1fccc9235
